### ISSUE TITLE
Support for Rails 7

### ISSUE THREAD

**Issue by rodrigotassinari** [emartech/ezlog#4]
The latest version of Ezlog ([v0.10.0](https://rubygems.org/gems/ezlog/versions/0.10.0)) doesn't work with Rails 7 applications. It errors on app startup with the message `uninitialized constant ActionView::LogSubscriber`.

From what I can understand, it seems `ActionView::LogSubscriber` isn't loaded by default by Rails on version 7. If I explicitly `require 'action_view/log_subscriber'`, Ezlog seems to work fine then.

I've made ir work with my project using [this fork](https://github.com/nuuvem/ezlog/tree/rails7-support), but I've not opened a pull request yet because I'm not sure if that's the best way to handle this. Any feedback is appreciated.

**Comment by zormandi** [comment]
Hi @rodrigotassinari ,

Sorry for the late answer but since I left Emarsys (the company that owns this repo) I can't actively maintain this project any more. The solution you suggested works fine but is forked from v0.10.0 which is not the latest version any more. This problem is already solved by v0.10.1 (PR: https://github.com/emartech/ezlog/pull/5) but only for Rails 6.1. I would use the same approach here, just extend the `case...when` to cover Rails 7 as well.

If you create a PR then let me know and I'll ask one of the maintainers to merge it.

(Btw, as a side note, I'm going to release a successor to Ezlog soon as an open-source project. It's called [Logcraft](https://github.com/zormandi/logcraft) so if you're interested, be sure to check it out.)

Cheers,
Z

**Comment by foldadamSAP** [comment]
Hi @rodrigotassinari as @zormandi's Logcraft gem turns out to work for us with Rails 7, we decided not to support ezlog anymore. We added a warning about this in the Readme and will archive the repository soon.
(earlier versions of ezlog will still be available)
